In [1]:
from numpy import set_printoptions, float32, eye, array, sqrt, copy, degrees
from math import sin, cos, atan2, pi

# 设置Numpy打印精度
set_printoptions(precision=3, suppress=True)

In [2]:
"""
将平移过程分别拆解成在X方向上平移，在Y方向上平移，在Z方向上平移
"""
def translation_x(dx):
    """沿X轴平移"""
    return float32([
        [1, 0, 0, dx],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

def translation_y(dy):
    """沿Y轴平移"""
    return float32([
        [1, 0, 0, 0],
        [0, 1, 0, dy],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

def translation_z(dz):
    """沿Z轴平移"""
    return float32([
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, dz],
        [0, 0, 0, 1]])

In [3]:
def rotate_x(gamma):
    """绕X轴旋转"""
    return array([
        [1, 0, 0, 0],
        [0, cos(gamma), -sin(gamma), 0],
        [0, sin(gamma), cos(gamma), 0],
        [0, 0, 0, 1]])

In [4]:
def rotate_y(beta):
    """绕Y轴旋转"""
    return array([
        [cos(beta), 0, sin(beta), 0],
        [0, 1, 0, 0],
        [-sin(beta), 0, cos(beta), 0],
        [0, 0, 0, 1]])

In [5]:
def rotate_z(alpha):
    """绕Z轴旋转"""
    return array([
        [cos(alpha), -sin(alpha), 0, 0],
        [sin(alpha), cos(alpha), 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [6]:
from math import radians

In [7]:
# 定义向量
p1 = array([0.5, 0.2, 0.8, 1]).reshape(-1, 1)
# 平移向量
q = array([0.5, 0, 0.2]).reshape(-1, 1)  # 平移向量
# 旋转角度
gamma = radians(30.0)  # 绕X轴旋转
beta = radians(-45.0)  # 绕Y轴旋转
alpha = radians(60.0)  # 绕Z轴旋转

In [8]:
"""
旋转：向量 * 旋转矩阵
平移：向量 * 平移矩阵
"""
# 向量绕X轴旋转 -->> 向量绕X轴平移
transformation_matrix  = rotate_x(gamma)
transformation_matrix = transformation_matrix.dot(translation_x(0.5))

In [9]:
# 向量绕Y轴旋转 -->> 向量绕Y轴平移
transformation_matrix = transformation_matrix.dot(rotate_y(beta))
transformation_matrix = transformation_matrix.dot(translation_y(0))

In [10]:
# 向量绕Z轴旋转 -->> 向量绕Z轴平移
transformation_matrix = transformation_matrix.dot(rotate_z(beta))
transformation_matrix = transformation_matrix.dot(translation_z(0.2))

In [11]:
# 打印变换矩阵
print(transformation_matrix)

[[ 0.5    0.5   -0.707  0.359]
 [-0.862  0.362 -0.354 -0.071]
 [ 0.079  0.787  0.612  0.122]
 [ 0.     0.     0.     1.   ]]


In [12]:
# 计算变换后的点
p2 = transformation_matrix.dot(p1)

In [13]:
p2

array([[ 0.143],
       [-0.712],
       [ 0.809],
       [ 1.   ]])